---
title: "Analysis Report"
author: "Svenja Kuster"
date: today
toc: true
abstract-title: "Research questions:"
abstract: "Does the new drug AH-27 lead to a greater reduction of systolic blood pressure (SBP) compared to standard care? Is a higher baseline SBP associated with a greater reduction in SBP? Do older patients have a reduced responsiveness to AH-27? Is there a sex difference in the response to AH-27?"
format:
  html:
    embed-resources: true
    number-sections: true
    code-fold: show
editor: visual
editor_options:
  chunk_output_type: console
execute:
  warning: false
  message: false
---

# Prepare Session and Import/Clean Data

```{r}
#| label: load-packages
#| echo: false
#| output: false

library(pastecs)
library(ggpubr); theme_set(theme_bw())
library(GGally)
library(performance)
library(MuMIn)
library(ggeffects)
library(knitr)
```

```{r}
#| label: import-and-clean-data
#| echo: false
#| output: false
sbp <- read.csv("./data/processed/hyper-tension.csv")
```

# Explore the Data

## numerically

## graphically

# Fit Candidate Models and Select the Best One

# Validate Preferred Model

# Interpret and Report Findings

# Store Session Information
